### PR TITLE
Different approach for dealing with notification data

### PR DESCRIPTION
**Pull request by gralin**
I had to sit down and try myself to deal with this problem. I came up with the below code. I've introduced a new class in place of StateTransition that doesn't require rewriting properties. I don't know if the naming is better than yours, so if you think state transition makes more sense we can rename it. Let me know what you think. Generaly other advantage is the generic nature (like you suggested in comment) because this way we can in the future introduce dedicated events on the main client class. We don't have unit tests and I don't have BACnet devices to test this.

### CODE REVIEW

**Comment by gralin** [comment]
https://github.com/ela-compil/BACnet/pull/21

**Comment by DarkStarDS9** [comment]
I like the List<Action<>> stuff :smiley:
If I turn on crazy-mode, I'd implement a constructor that takes `IEnumerable<KeyValuePair<MemberExpression, object>>` to enable setting of read-only values too, but Expressions are painfully slow (about 20x slower than using `Action<>`s) :rofl: 

What I don't like:
1. having `EventValues` in `NotificationDataExtended` instead of just the generic class. It serves no purpose (or does it?) and suggests that there *might* be something present in ACK-Events too, which never is (according to the standard).
2. naming :wink: I tried to find names that correlate to the wording in the standard, especially Table 13-3 "Event Notification Service Parameter Values" which lists parameters for "Event State Transition" vs "Acknowledgment Transition".

**Comment by gralin** [comment]
I'm glad you like the change 😃 I have reverted the naming and removed ```EventValues``` from ```NotificationDataExtended```, I will trust you on this. And lets keep the crazy mode to minimum 🤣

**Comment by DarkStarDS9** [comment]
Has been integrated in upstream

**Pull request closed without merging**
